"""add_order_payment_pickup_garment_service_lining

Revision ID: 439ccd9639e5
Revises: 66e55d2898b7
Create Date: 2026-03-17 23:10:05.163480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439ccd9639e5'
down_revision: Union[str, Sequence[str], None] = '66e55d2898b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laundry_order_items', sa.Column('service_type', sa.String(), nullable=True))
    op.add_column('laundry_order_items', sa.Column('fabric_type', sa.String(), nullable=True))
    op.add_column('laundry_order_items', sa.Column('has_lining', sa.Boolean(), nullable=True))
    op.add_column('laundry_orders', sa.Column('pickup_type', sa.String(), nullable=True))
    op.add_column('laundry_orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('laundry_orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('laundry_orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laundry_orders', 'discount_amount')
    op.drop_column('laundry_orders', 'payment_status')
    op.drop_column('laundry_orders', 'payment_method')
    op.drop_column('laundry_orders', 'pickup_type')
    op.drop_column('laundry_order_items', 'has_lining')
    op.drop_column('laundry_order_items', 'fabric_type')
    op.drop_column('laundry_order_items', 'service_type')
    # ### end Alembic commands ###
